#!/bin/bash
#
# BMS503 Pipeline — Clean Script
# Removes all regenerable outputs, leaving only source data and pipeline code.
# After running, zip the folder for transfer (~5 MB vs 1+ GB).
# Re-run ./run_pipeline.sh on the receiving machine to regenerate everything.
#
# What is KEPT:
#   data/raw/              — input FASTQ files (not regenerable)
#   data/reference/        — reference genome FASTA only (indexes are removed)
#   data/reference_db/     — master tree + alignment (enables incremental runs)
#   data/nextclade_db/     — local Nextclade dataset if present (saves re-download)
#   config/                — pipeline configuration
#   workflow/              — scripts and rules
#   Snakefile              — workflow definition
#   *.sh / *.md            — entry scripts and documentation
#
# What is REMOVED:
#   results/               — all pipeline outputs (fully regenerable)
#   logs/                  — all log files
#   .snakemake/            — Snakemake cache (non-portable)
#   data/reference/*.{0123,amb,ann,bwt.2bit.64,pac,fai} — reference indexes
#   **/__pycache__ / *.pyc — Python bytecode

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}This will permanently delete all pipeline outputs and logs.${NC}"
echo    "The following will be removed:"
echo    "  results/    logs/    .snakemake/    reference index files"
echo    "Raw FASTQ files, reference FASTA, reference_db, and all code are preserved."
echo ""
read -r -p "Continue? [y/N] " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""

# Pipeline outputs
if [ -d results ]; then
    echo "Removing results/..."
    rm -rf results/
fi

# Logs
if [ -d logs ]; then
    echo "Removing logs/..."
    rm -rf logs/
fi

# Snakemake cache
if [ -d .snakemake ]; then
    echo "Removing .snakemake cache..."
    rm -rf .snakemake/
fi

# Reference genome indexes (regenerated by bwa-mem2 index + samtools faidx)
echo "Removing reference index files..."
find data/reference -type f ! -name "*.fasta" ! -name "*.fa" ! -name "*.fna" ! -name "*.ffn" -delete 2>/dev/null || true

# Python bytecode
echo "Removing Python cache..."
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find . -name "*.pyc" -delete 2>/dev/null || true

echo ""
echo -e "${GREEN}Done. Remaining directory sizes:${NC}"
du -sh data/ config/ workflow/ Snakefile *.sh *.md 2>/dev/null | sort -h
echo ""
echo "To run the pipeline: ./run_pipeline.sh"
